export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export default {
  ADD_TODO,
  TOGGLE_TODO,
  SET_VISIBILITY_FILTER
};
